# Generated by Django 3.1.2 on 2021-02-26 11:10
import csv

from django.db import migrations

from core.shared.base.domain.uuid import UUID


def brands_data(apps, schema_editor):
    BrandModel = apps.get_model('core', 'BrandModel')
    with open('core/migrations/brands.csv') as csv_file:
        reader = csv.reader(csv_file)
        header = next(reader)

        brands = []

        for row in reader:
            brand = BrandModel(
                id=UUID.random(),
                name=row[0]
            )

            brands.append(brand)

        BrandModel.objects.bulk_create(brands)


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(brands_data),
    ]
