# Generated by Django 3.1.2 on 2021-02-26 12:13
import csv

from django.db import migrations

from core.shared.base.domain.uuid import UUID


def types_data(apps, schema_editor):
    TypeModel = apps.get_model('core', 'TypeModel')
    with open('core/migrations/types.csv') as csv_file:
        reader = csv.reader(csv_file)
        header = next(reader)

        types = []

        for row in reader:
            brand = TypeModel(
                id=UUID.random(),
                name=row[0]
            )

            types.append(brand)

        TypeModel.objects.bulk_create(types)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_typemodel'),
    ]

    operations = [
        migrations.RunPython(types_data),
    ]
