version: '3'

services:
  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
    volumes:
      - ./.ganache_data:/ganache_data
    command: "--seed abcd --defaultBalanceEther 100000000 --db=/ganache_data"
