server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: catalog-service
          uri: http://localhost:8000/
          predicates:
            - Path=/catalog/**
          filters:
            - StripPrefix=1
        - id: consumerModule
          uri: http://localhost:8082/
          predicates:
            - Path=/consumer/**