# Generated by Django 3.1.2 on 2021-04-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210226_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('brand_id', models.UUIDField()),
                ('type_id', models.UUIDField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('picture_file_name', models.CharField(max_length=300)),
                ('price', models.BigIntegerField()),
            ],
            options={
                'db_table': 'item',
            },
        ),
    ]
